export const LOG_OUT = 'LOG_OUT';
export const TOGGLE_DRAWER= 'TOGGLE_DRAWER';
export const SNACKBAR_OPEN= 'SNACKBAR_OPEN';
export const SNACKBAR_CLOSE= 'SNACKBAR_CLOSE';
export const SET_SNACKBAR_MESSAGE= 'SET_SNACKBAR_MESSAGE';
export const LOG_IN= 'LOG_IN';
export const UPDATE_SELECTED_TRIP= 'UPDATE_SELECTED_TRIP';
export const SET_INVITE_CODE= 'ADD_INVITE_CODE';
export const REMOVE_INVITE_CODE= 'REMOVE_INVITE_CODE';
export const UPDATE_RECENT_TRIPS= 'UPDATE_RECENT_TRIPS';
export const TOGGLE_CHAT_ROOM_OPEN= 'TOGGLE_CHAT_ROOM_OPEN';
export const CHAT_ROOM_OPEN= 'CHAT_ROOM_OPEN';
export const CHAT_ROOM_CLOSE= 'CHAT_ROOM_CLOSE';
export const DRAWER_EXTEND= 'DRAWER_EXTEND';
export const DRAWER_FOLD= 'DRAWER_FOLD';
export const UPDATE_USER_INFO= 'UPDATE_USER_INFO';

